### PR TITLE
[KOGITO-8799]  Add Kubernetes security profile to Kaniko and builder pods

### PR DESCRIPTION
**Pull request by desmax74**
See:https://issues.redhat.com/browse/KOGITO-8799

**Description of the change:**

**Motivation for the change:**

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

### CODE REVIEW

**Comment by desmax74** [comment]
jenkins test this

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
And how about the warmer pod?

**Comment by desmax74** [comment]
@ricardozanini the warmer pod iirc is in the operator

**Comment by ricardozanini** [comment]
> @ricardozanini the warmer pod iirc is in the operator

Are we creating it or the Kaniko API? Nevertheless, a PR for the operator is coming then?

**Comment by desmax74** [comment]
@ricardozanini the operator pr is here: https://github.com/kiegroup/kogito-serverless-operator/pull/85

**Review by davidesalerno — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Pull request merged**
